parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Category Forms.
    #
    map2u_forum.form.type.category_create:
        class: %map2u_forum.form.type.category_create.class%
        arguments:
            - %map2u_forum.entity.category.class%
            - %map2u_forum.entity.forum.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.category_create:
        class: %map2u_forum.form.handler.category_create.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.category_create
            - @map2u_forum.model.category

    map2u_forum.form.type.category_update:
        class: %map2u_forum.form.type.category_update.class%
        arguments:
            - %map2u_forum.entity.category.class%
            - %map2u_forum.entity.forum.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.category_update:
        class: %map2u_forum.form.handler.category_update.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.category_update
            - @map2u_forum.model.category

    map2u_forum.form.type.category_delete:
        class: %map2u_forum.form.type.category_delete.class%
        arguments:
            - %map2u_forum.entity.category.class%

    map2u_forum.form.handler.category_delete:
        class: %map2u_forum.form.handler.category_delete.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.category_delete
            - @map2u_forum.model.category
