parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Forum Forms.
    #
    map2u_forum.form.type.forum_create:
        class: %map2u_forum.form.type.forum_create.class%
        arguments:
            - %map2u_forum.entity.forum.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.forum_create:
        class: %map2u_forum.form.handler.forum_create.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.forum_create
            - @map2u_forum.model.forum

    map2u_forum.form.type.forum_update:
        class: %map2u_forum.form.type.forum_update.class%
        arguments:
            - %map2u_forum.entity.forum.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.forum_update:
        class: %map2u_forum.form.handler.forum_update.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.forum_update
            - @map2u_forum.model.forum

    map2u_forum.form.type.forum_delete:
        class: %map2u_forum.form.type.forum_delete.class%
        arguments:
            - %map2u_forum.entity.forum.class%

    map2u_forum.form.handler.forum_delete:
        class: %map2u_forum.form.handler.forum_delete.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.forum_delete
            - @map2u_forum.model.forum
