parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Board Forms.
    #
    map2u_forum.form.type.board_create:
        class: %map2u_forum.form.type.board_create.class%
        arguments:
            - %map2u_forum.entity.board.class%
            - %map2u_forum.entity.category.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.board_create:
        class: %map2u_forum.form.handler.board_create.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.board_create
            - @map2u_forum.model.board

    map2u_forum.form.type.board_update:
        class: %map2u_forum.form.type.board_update.class%
        arguments:
            - %map2u_forum.entity.board.class%
            - %map2u_forum.entity.category.class%
            - @map2u_forum.component.helper.role

    map2u_forum.form.handler.board_update:
        class: %map2u_forum.form.handler.board_update.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.board_update
            - @map2u_forum.model.board

    map2u_forum.form.type.board_delete:
        class: %map2u_forum.form.type.board_delete.class%
        arguments:
            - %map2u_forum.entity.board.class%

    map2u_forum.form.handler.board_delete:
        class: %map2u_forum.form.handler.board_delete.class%
        arguments:
            - @event_dispatcher
            - @form.factory
            - @map2u_forum.form.type.board_delete
            - @map2u_forum.model.board
