parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Managers.
    #

    map2u_forum.manager.forum:
        class: %map2u_forum.manager.forum.class%
        arguments:
            - @map2u_forum.gateway.forum

    map2u_forum.manager.category:
        class: %map2u_forum.manager.category.class%
        arguments:
            - @map2u_forum.gateway.category

    map2u_forum.manager.board:
        class: %map2u_forum.manager.board.class%
        arguments:
            - @map2u_forum.gateway.board

    map2u_forum.manager.topic:
        class: %map2u_forum.manager.topic.class%
        arguments:
            - @map2u_forum.gateway.topic
            - @map2u_forum.component.helper.post_lock

    map2u_forum.manager.post:
        class: %map2u_forum.manager.post.class%
        arguments:
            - @map2u_forum.gateway.post
            - @map2u_forum.component.helper.post_lock

    map2u_forum.manager.registry:
        class: %map2u_forum.manager.registry.class%
        arguments:
            - @map2u_forum.gateway.registry

    map2u_forum.manager.subscription:
        class: %map2u_forum.manager.subscription.class%
        arguments:
            - @map2u_forum.gateway.subscription
