parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Repositories.
    #

    map2u_forum.repository.forum:
        class: %map2u_forum.repository.forum.class%
        arguments:
            - @map2u_forum.gateway.forum

    map2u_forum.repository.category:
        class: %map2u_forum.repository.category.class%
        arguments:
            - @map2u_forum.gateway.category

    map2u_forum.repository.board:
        class: %map2u_forum.repository.board.class%
        arguments:
            - @map2u_forum.gateway.board

    map2u_forum.repository.topic:
        class: %map2u_forum.repository.topic.class%
        arguments:
            - @map2u_forum.gateway.topic

    map2u_forum.repository.post:
        class: %map2u_forum.repository.post.class%
        arguments:
            - @map2u_forum.gateway.post

    map2u_forum.repository.registry:
        class: %map2u_forum.repository.registry.class%
        arguments:
            - @map2u_forum.gateway.registry

    map2u_forum.repository.subscription:
        class: %map2u_forum.repository.subscription.class%
        arguments:
            - @map2u_forum.gateway.subscription
