parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Models.
    #

    map2u_forum.model.forum:
        class: %map2u_forum.model.forum.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.forum
            - @map2u_forum.manager.forum

    map2u_forum.model.category:
        class: %map2u_forum.model.category.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.category
            - @map2u_forum.manager.category

    map2u_forum.model.board:
        class: %map2u_forum.model.board.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.board
            - @map2u_forum.manager.board

    map2u_forum.model.topic:
        class: %map2u_forum.model.topic.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.topic
            - @map2u_forum.manager.topic

    map2u_forum.model.post:
        class: %map2u_forum.model.post.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.post
            - @map2u_forum.manager.post

    map2u_forum.model.registry:
        class: %map2u_forum.model.registry.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.registry
            - @map2u_forum.manager.registry

    map2u_forum.model.subscription:
        class: %map2u_forum.model.subscription.class%
        arguments:
            - @event_dispatcher
            - @map2u_forum.repository.subscription
            - @map2u_forum.manager.subscription
