parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Twig Extensions.
    #

    map2u_forum.component.twig_extension.board_list:
        class: %map2u_forum.component.twig_extension.board_list.class%
        arguments:
            - @map2u_forum.model.category
        tags:
            - { name: twig.extension }

    map2u_forum.component.twig_extension.authorizer:
        class: %map2u_forum.component.twig_extension.authorizer.class%
        arguments:
            - @map2u_forum.component.security.authorizer
        tags:
            - { name: twig.extension }

    map2u_forum.component.twig_extension.forum_global:
        class: %map2u_forum.component.twig_extension.forum_global.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
